language:
- objective-c
env:
  global:
  - BUILD_COMMIT='latest-tag'  # comment out to build version in submodule
  - REPO_DIR=netcdf4-python
  - SZIP_VERSION=2.1
  - HDF5_VERSION=1.8.13
  - NETCDF_VERSION=4.3.3.1
  - NETCDF_CXX_VERSION=4.2.1
  matrix:
  - VERSION=2.7.9 NUMPY_VERSION=1.6.2 # tune to taste
  - VERSION=3.3.5 NUMPY_VERSION=1.7.1
  - VERSION=3.4.3 NUMPY_VERSION=1.7.1
install:
  - source terryfy/travis_tools.sh
  - get_python_environment macpython $VERSION venv
  - pip install delocate numpy==$NUMPY_VERSION
  - source terryfy/library_installers.sh
  - clean_builds
  - standard_install szip $SZIP_VERSION .tar.gz szip- --enable-encoding=no
  - standard_install hdf5 $HDF5_VERSION .tar.bz2 hdf5- --with-szlib=$BUILD_PREFIX
  - standard_install netcdf-c $NETCDF_VERSION .tar.gz netcdf-
  - if [ -n "$BUILD_COMMIT" ]; then
        checkout_commit $REPO_DIR $BUILD_COMMIT;
    fi
  - cd $REPO_DIR
  - python setup.py bdist_wheel
  - delocate-listdeps dist/*.whl # lists library dependencies
  - delocate-wheel dist/*.whl # copies library dependencies into wheel
  - delocate-addplat --rm-orig -x 10_9 -x 10_10 dist/*.whl
  - pip install dist/*.whl
script:
  - cd test
  # Run the tests
  - python run_all.py
  - cd ..
before_deploy: cd $REPO_DIR/dist
deploy:
  provider: cloudfiles
  username: travis-worker
  api_key:
    secure: "LCjZLORUfF9gZx5Bw0RYZacLV6wgdN+vpNggJmt36FyFwXNdYfc3qT98XT83D29rNTFW7wh3N8WsfWm4zWn8X/N7Ndl545Kq3zIJwnlaHdnd8a7LT6TKXEdrSTPnZQL5Uqxffj2DYYuMvXkTfNm47f3caxQdXVeLTC5YGtTWiBY="
  region: ORD
  container: wheels
  skip_cleanup: true
